CREATE DATABASE BANGIAY
USE BANGIAY

IF OBJECT_ID('DIEMTHANHVIEN') IS NOT NULL
DROP TABLE DIEMTHANHVIEN
CREATE TABLE DIEMTHANHVIEN(
MAKH CHAR(20) PRIMARY KEY,
TENKH NVARCHAR(50),
SDT VARCHAR(15),
DIEMMUAHANG VARCHAR(30),
LUOTMUAHANG VARCHAR(30),
)
IF OBJECT_ID('KHUYENMAI') IS NOT NULL
DROP TABLE KHUYENMAI
CREATE TABLE KHUYENMAI(
MAKM CHAR(20) PRIMARY KEY,
TENKM NVARCHAR(50),
SOTIENGIAM DECIMAL(20,0) DEFAULT 0,
NGAYBD DATE,
NGAYKT DATE,
)
IF OBJECT_ID('NHANVIEN') IS NOT NULL
DROP TABLE NHANVIEN
CREATE TABLE NHANVIEN(
MANV CHAR(20) PRIMARY KEY,
TENNV NVARCHAR(50),
GIOITINH BIT,
CHUCVU NVARCHAR(50),
EMAIL VARCHAR(50),
QUEQUAN NVARCHAR(50),
NGAYSINH DATE,
TAIKHOAN VARCHAR(50),
MATKHAU VARCHAR(50),
)
IF OBJECT_ID('DANHMUC') IS NOT NULL
DROP TABLE DANHMUC
CREATE TABLE DANHMUC(
MADANHMUC CHAR(20) PRIMARY KEY,
TENDANHMUC NVARCHAR(50),
MOTA NVARCHAR(50),
)
IF OBJECT_ID('ANH') IS NOT NULL
DROP TABLE ANH
CREATE TABLE ANH(
MASP CHAR(20) PRIMARY KEY,
TENSP NVARCHAR(50),
URL1 IMAGE,
URL2 IMAGE,
URL3 IMAGE,
)
IF OBJECT_ID('TRANGTHAI') IS NOT NULL
DROP TABLE TRANGTHAI
CREATE TABLE TRANGTHAI(
MAHD CHAR(20) PRIMARY KEY,
TRANGTHAI NVARCHAR(50),
)
IF OBJECT_ID('HOADONTRA') IS NOT NULL
DROP TABLE HOADONTRA
CREATE TABLE HOADONTRA(
MAHD CHAR(20) PRIMARY KEY,
MAHDDT CHAR(20),
NGAYTAO DATE,
NGAYLAPHD DATE,
TONGTIEN MONEY,
)
IF OBJECT_ID('KHACHHANG') IS NOT NULL
DROP TABLE KHACHHANG
CREATE TABLE KHACHHANG(
MAKH CHAR(20) PRIMARY KEY,
TENKH NVARCHAR(50),
SDT VARCHAR(15),
LOAIKH NVARCHAR(50),
DIEMTHANHVIEN CHAR(15),
FOREIGN KEY (MAKH) REFERENCES DIEMTHANHVIEN
)
IF OBJECT_ID('HOADON') IS NOT NULL
DROP TABLE HOADON 
CREATE TABLE HOADON(
MAHD CHAR(20) PRIMARY KEY,
NGAYTAO DATE,
TONGTIEN MONEY,
SOTIENGIAM MONEY,
GHICHU NVARCHAR(50),
MAKH CHAR(20),
MAKM CHAR(20),
MANV CHAR(20),
FOREIGN KEY (MAKH) REFERENCES KHACHHANG,
FOREIGN KEY (MAKM) REFERENCES KHUYENMAI,
FOREIGN KEY (MANV) REFERENCES NHANVIEN,
FOREIGN KEY (MAHD) REFERENCES TRANGTHAI,
FOREIGN KEY (MAHD) REFERENCES HOADONTRA
)
IF OBJECT_ID('SANPHAM') IS NOT NULL
DROP TABLE SANPHAM
CREATE TABLE SANPHAM(
MASP CHAR(20) PRIMARY KEY,
TRANGTHAI NVARCHAR(50),
MOTA NVARCHAR(50),
MADANHMUC CHAR(20),
SIZE VARCHAR(60),
URLANH IMAGE,
GIA MONEY,
TENSP NVARCHAR(50),
FOREIGN KEY (MADANHMUC) REFERENCES DANHMUC,
FOREIGN KEY (MASP) REFERENCES ANH
)
IF OBJECT_ID('HOADONCHITIET') IS NOT NULL
DROP TABLE HOADONCHITIET
CREATE TABLE HOADONCHITIET(
MAHD CHAR(20),
MASP CHAR(20),
SLMUA INT,
GIA MONEY,
TENSP NVARCHAR(50),
FOREIGN KEY (MAHD) REFERENCES HOADON,
FOREIGN KEY (MASP) REFERENCES SANPHAM
)
IF OBJECT_ID('GIOHANG') IS NOT NULL
DROP TABLE GIOHANG
CREATE TABLE GIOHANG(
MAGH CHAR(20) PRIMARY KEY,
NGAYTAO DATE,
GHICHU NVARCHAR(50),
SOTIENGIAM MONEY,
MAKH CHAR(20),
MAKM CHAR(20),
MANV CHAR(20),
TONGTIEN MONEY,
FOREIGN KEY (MAKH) REFERENCES KHACHHANG
)
IF OBJECT_ID('GIOHANGCHITIET') IS NOT NULL
DROP TABLE GIOHANGCHITIET
CREATE TABLE GIOHANGCHITIET(
MAGH CHAR(20),
MASP CHAR(20),
SLMUA INT,
DONGIA MONEY,
TENSP NVARCHAR(50),
FOREIGN KEY (MAGH) REFERENCES GIOHANG,
FOREIGN KEY (MASP) REFERENCES SANPHAM
)