/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Repository.AccountRepository;
import Service.EmailSender;
import Utilities.DBcontext;
import Utilities.SQLServerConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Huy PC
 */
public class FormQuenPass extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    EmailSender email=new EmailSender();
    AccountRepository acc=new AccountRepository();
    public FormQuenPass() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layoutChinh = new javax.swing.JPanel();
        pannelHeader = new javax.swing.JPanel();
        titleHeader = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btndangnhap = new javax.swing.JButton();
        btnquenpass = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        setResizable(false);

        layoutChinh.setBackground(new java.awt.Color(244, 246, 248));
        layoutChinh.setMaximumSize(new java.awt.Dimension(1920, 1080));
        layoutChinh.setMinimumSize(new java.awt.Dimension(1920, 1080));
        layoutChinh.setPreferredSize(new java.awt.Dimension(1920, 1080));

        pannelHeader.setBackground(new java.awt.Color(242, 157, 56));
        pannelHeader.setMaximumSize(new java.awt.Dimension(1920, 64));
        pannelHeader.setMinimumSize(new java.awt.Dimension(1920, 64));
        pannelHeader.setPreferredSize(new java.awt.Dimension(1920, 64));

        titleHeader.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        titleHeader.setForeground(new java.awt.Color(255, 255, 255));
        titleHeader.setText("PHẦM MỀM QUẢN LÝ BÁN HÀNG");
        titleHeader.setMaximumSize(new java.awt.Dimension(297, 22));
        titleHeader.setMinimumSize(new java.awt.Dimension(297, 22));
        titleHeader.setPreferredSize(new java.awt.Dimension(297, 22));

        javax.swing.GroupLayout pannelHeaderLayout = new javax.swing.GroupLayout(pannelHeader);
        pannelHeader.setLayout(pannelHeaderLayout);
        pannelHeaderLayout.setHorizontalGroup(
            pannelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelHeaderLayout.createSequentialGroup()
                .addGap(844, 844, 844)
                .addComponent(titleHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(757, Short.MAX_VALUE))
        );
        pannelHeaderLayout.setVerticalGroup(
            pannelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelHeaderLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(titleHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setMaximumSize(new java.awt.Dimension(480, 470));
        LoginPanel.setMinimumSize(new java.awt.Dimension(480, 470));
        LoginPanel.setPreferredSize(new java.awt.Dimension(480, 470));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(38, 50, 56));
        jLabel1.setText("Vui lòng nhập tài khoản (Email) của bạn ");
        jLabel1.setMaximumSize(new java.awt.Dimension(378, 28));
        jLabel1.setMinimumSize(new java.awt.Dimension(378, 28));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(378, 28));

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setMaximumSize(new java.awt.Dimension(423, 1));
        jPanel1.setMinimumSize(new java.awt.Dimension(423, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(423, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        btndangnhap.setBackground(new java.awt.Color(242, 157, 56));
        btndangnhap.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        btndangnhap.setForeground(new java.awt.Color(255, 255, 255));
        btndangnhap.setText("ĐĂNG NHẬP");
        btndangnhap.setBorder(null);
        btndangnhap.setMaximumSize(new java.awt.Dimension(423, 46));
        btndangnhap.setMinimumSize(new java.awt.Dimension(423, 46));
        btndangnhap.setPreferredSize(new java.awt.Dimension(423, 46));
        btndangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangnhapActionPerformed(evt);
            }
        });

        btnquenpass.setBackground(new java.awt.Color(242, 157, 56));
        btnquenpass.setForeground(new java.awt.Color(255, 255, 255));
        btnquenpass.setText("seed email(cập nhật lại mật khẩu)");
        btnquenpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquenpassActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(38, 50, 56));
        jLabel2.setText("sẽ có mật khẩu mới gửi đến mail của bạn");
        jLabel2.setMaximumSize(new java.awt.Dimension(378, 28));
        jLabel2.setMinimumSize(new java.awt.Dimension(378, 28));
        jLabel2.setName(""); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(378, 28));

        txtUsername.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(84, 110, 122));
        txtUsername.setText("  Tên tài khoản (Email)");
        txtUsername.setToolTipText("");
        txtUsername.setMaximumSize(new java.awt.Dimension(423, 56));
        txtUsername.setMinimumSize(new java.awt.Dimension(423, 56));
        txtUsername.setPreferredSize(new java.awt.Dimension(423, 56));
        txtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsernameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btndangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(LoginPanelLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnquenpass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(0, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnquenpass, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btndangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layoutChinhLayout = new javax.swing.GroupLayout(layoutChinh);
        layoutChinh.setLayout(layoutChinhLayout);
        layoutChinhLayout.setHorizontalGroup(
            layoutChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layoutChinhLayout.createSequentialGroup()
                .addComponent(pannelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layoutChinhLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(706, 706, 706))
        );
        layoutChinhLayout.setVerticalGroup(
            layoutChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layoutChinhLayout.createSequentialGroup()
                .addComponent(pannelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 458, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(layoutChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layoutChinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseClicked
        // TODO add your handling code here:
        if (txtUsername.getForeground().equals(Color.decode("#546E7A"))) {
            txtUsername.setText("");
            txtUsername.setForeground(Color.BLACK);
            
        }
    }//GEN-LAST:event_txtUsernameMouseClicked

    private void btndangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangnhapActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btndangnhapActionPerformed

    private void btnquenpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquenpassActionPerformed
        // TODO add your handling code here:
        String query = "select * from nhanvien where taikhoan=?";
        String tk=txtUsername.getText();
        int check = 0;
        try ( Connection con = DBcontext.getConnection();  PreparedStatement ps = con.prepareStatement(query)) {
            ps.setString(1, txtUsername.getText().toString().toLowerCase());
            ResultSet rs = ps.executeQuery();
            if (txtUsername.getText().trim().isEmpty()) {
                rs.close();
                JOptionPane.showMessageDialog(rootPane, "cần nhập tk và mk");
            } else if (rs.next()) {
                rs.close();
                JOptionPane.showMessageDialog(rootPane, "seen email thành công");
                email.sendemail(tk);
                acc.updatepass(tk);
            } else {
                rs.close();
                JOptionPane.showMessageDialog(rootPane, "đăng nhập không thành công");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnquenpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuenPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuenPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuenPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuenPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuenPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JButton btndangnhap;
    private javax.swing.JButton btnquenpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel layoutChinh;
    private javax.swing.JPanel pannelHeader;
    private javax.swing.JLabel titleHeader;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
